### ISSUE TITLE
You broke my badges (which used shortcut reference syntax)

### ISSUE THREAD

**Issue by phs** [github/cmark#11]
In the old github-flavored markdown, this used to do the Right Thing:

```
[![Build Status][build-status-badge]][build-status-link]
[build-status-badge]: https://travis-ci.org/myorg/myrepo.svg?branch=master
[build-status-link]: https://travis-ci.org/myorg/myrepo
```

Now the markup appears verbatim in rendered output (sans newlines).

Can I have it back?  Or at least, what _should_ I do?

**Comment by kivikakk** [comment]
Try inserting a newline, as follows:

``` markdown
[![Build Status][build-status-badge]][build-status-link]

[build-status-badge]: https://travis-ci.org/myorg/myrepo.svg?branch=master
[build-status-link]: https://travis-ci.org/myorg/myrepo
```

The result is as follows:

[![Build Status][build-status-badge]][build-status-link]

[build-status-badge]: https://travis-ci.org/myorg/myrepo.svg?branch=master
[build-status-link]: https://travis-ci.org/myorg/myrepo

(This is required because reference links are a separate block element.)

**Comment by phs** [comment]
And it work! Thank you.
