### ISSUE TITLE
Manpage naming confusion (e.g. `make install` does not work)

### ISSUE THREAD

**Issue by hzeller** [github/cmark#20]
Currently, `make install` does not work, as the manpages named in `man/man3` has been named `cmark-gfm.3`, but the Makefile still refers to cmark.3 (see patch below).

But this seems to be even more messy: the binary created is called `cmark-gfm`, so naturally, the cmark.1 should be called also cmark-gfm.1

Then there is the content of the manpage itself. It still refers to cmark instead of cmark gfm. Since I don't know what the intention and final naming goal is, I couldn't roll a pull request out of that. Anyway, first suggested patch below, but all the other things above would need attention too.

```
--- a/man/CMakeLists.txt
+++ b/man/CMakeLists.txt
@@ -5,6 +5,6 @@ include(GNUInstallDirs)
   install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/man1/cmark.1
     DESTINATION ${CMAKE_INSTALL_MANDIR}/man1)
 
-  install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/man3/cmark.3
+  install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/man3/cmark-gfm.3
     DESTINATION ${CMAKE_INSTALL_MANDIR}/man3)
 endif(NOT MSVC)
```

**Comment by kivikakk** [comment]
Thank you very much for the report! This has been addressed in af15113; I've fixed up `cmark-gfm(1)`. `cmark-gfm(3)` still refers to `cmark` a lot because it's generated from the source itself, and I don't want to apply a huge delta between this fork and the source by global replace, but the major issues are fixed.
