### ISSUE TITLE
Where is the tasklist extension?

### ISSUE THREAD

**Issue by zmwangx** [github/cmark#23]
At the moment (`0.27.1.gfm.0`), the `tasklist` extension does not show up in `--list-extensions`; its test case in `test/spec.txt` is disabled; and it doesn't seem to be mentioned anywhere else in the code base. Am I right it's not included in the code base? Any plan to release it?

**Comment by kivikakk** [comment]
The tasklist extension isn't actually implemented in `cmark` itself; we perform this transformation in our (Ruby) user content stack, in such a way that conforms to the (quite loose) specification. It's not super likely that we'd reimplement it in C at this stage, as the benefit to us would be minimal.

The nature of task lists is that they are quite specific to your implementation — for example, we render our checkboxes disabled, and with specific classes so that JavaScript on the page can attach events to them and re-enable them, for AJAX-y updating of the Markdown contents when they're checked and unchecked. So the likelihood is you'd be best off implementing this yourself anyway, for your particular purpose.

**Comment by zmwangx** [comment]
Yeah makes sense, thanks for responding.

**Comment by kivikakk** [comment]
(Of course, there can be some differing on this opinion — I have implemented `tasklist` in my [Rust CommonMark library](https://github.com/kivikakk/comrak/blob/1203abc192847c960bddcdd785a03db58205c3c7/src/parser/mod.rs#L1104-L1138), but it's a really minimal implementation and isn't necessarily useful to many people without further post-processing.)

**Comment by zmwangx** [comment]
Cool, I'll check it out.
