### ISSUE TITLE
How to deal with tabs?

### ISSUE THREAD

**Issue by ahmed-taj** [github/cmark#59]
The spec says:

> Tabs in lines are not expanded to spaces. However, in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.
> 
> Thus, for example, a tab can be used instead of four spaces in an indented code block. (Note, however, that internal tabs are passed through as literal tabs, not expanded to spaces.)
>
> `→foo→baz→→bim`
> 
> `<pre><code>foo→baz→→bim</code></pre>`

Later the spec also says:
> In the following case > is followed by a tab, which is treated as if it were expanded into three spaces. Since one of these spaces is considered part of the delimiter, foo is considered to be indented six spaces inside the block quote context, so we get an indented code block starting with two spaces.
>
>     .-. foo
>     ...-. bar
>     →.-.baz
("." => space)

I would like to know in which cases exactly do we consider tab as 4? 3? 2? spaces? I'm building a parser  but I think that part of the spec is confusing!

**Comment by kivikakk** [comment]
Where whitespace count is used to define block structure, it's defined as expanded into as many spaces as needed reach the next tabstop of 4 spaces.  So for instance:

> ```
> →hi
> a→hi
> ab→hi
> abc→hi
> abcd→hi
> ```

Could be considered as equivalent to:

> ```
> ....hi
> a...hi
> ab..hi
> abc.hi
> abcd....hi
> ```

Does this make sense?

**Comment by ahmed-taj** [comment]
@kivikakk  umm.. not sure yet!

Let's take the folllowing example( [#9](https://github.github.com/gfm/#example-9) in the spec):
```
·-·foo
···-·bar
→·-·baz
```

AFAIK, it makes sense to treat the tab (→) as if it were expanded into 3 spaces, which makes `baz` a list item in the same level as `bar`, but something else happens here:
```
<ul>
<li>foo
<ul>
<li>bar
<ul>
<li>baz</li>
</ul>
</li>
</ul>
</li>
</ul>
``` 

May you explain why?

**Comment by kivikakk** [comment]
Sure! It gets expanded like this:

```
.-.foo
...-.bar
.....-.baz
```

Which gives the HTML rendering you're seeing. This is because the tab is at the very first column, and so inserts a full 4 spaces to reach the next tabstop of 4 spaces.

In other words, the number of spaces a tab will be considered as equivalent to is calculated as following:

``` c
spaces = 4 - (current_column % 4);
```

So in column 0, it's `4 - (0 % 4) = 4` spaces, in column 1 it's `4 - (1 % 4) = 3`, etc., until we hit column 4, where we get `4 - (4 % 4) = 4 - 0 = 4` spaces again.

Some relevant code can be seen in `blocks.c`:

https://github.com/github/cmark/blob/07fe00f38e78846bc0760cb02a3b1441dffc9b6d/src/blocks.c#L716

(There are a few places we make this calculation.)

Let me know if I can explain it any better.

**Comment by ahmed-taj** [comment]
@kivikakk Thanks, it makes sense now

I really appreciate your effort :)

**Comment by ahmed-taj** [comment]
Oh @kivikakk , I forgot to ask for your permission whether or not to add your as a contributor in the little [gfmc](/ahmed-taj/gfmc#contributors) package (based on [all-contributors](https://github.com/kentcdodds/all-contributors) spec by Kent C. Dodds), but I think your answer above is actually a great contribution!

Tell me if you feel uncomfortable about this

**Comment by kivikakk** [comment]
Oh, thank you! I'm honoured. :heart:
