### ISSUE TITLE
Specs for GFM auto-identifiers for headers

### ISSUE THREAD

**Issue by xoofx** [github/cmark#65]
Hi,
In [markdig](https://github.com/lunet-io/markdig) markdown parser, I have a mode for generating auto-identifiers for headers, similar to github, but I'm currently using a rule closer to what [pandoc is doing](http://pandoc.org/MANUAL.html#header-identifiers)

I would like to add also support for github auto-identifiers for header. I have found that the [autolink in GFM has a spec](https://github.github.com/gfm/#autolinks-extension-) but failing to see the auto-identifier.

Have you implemented this in cmark? Where is the code that is handling this part so that I could replicate the behavior? (or if it is not in cmark, can you point me where it was previously implemented?)

Thanks!

**Comment by xoofx** [comment]
Found this code https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb
Is it the correct one?

**Comment by kivikakk** [comment]
It is based on that code — and matches its behaviour 100% — though that's not the literal code we use any more, which is to say it _could_ change in the future. We care about backwards compatibility here, though, so it's super unlikely that it would.

(It happens in a post-processing stage way after Markdown to HTML conversion is done, long past `cmark` itself, which is why it's not part of the Markdown/GFM spec — i.e. it happens to all headers, regardless of whether they were first written as Markdown or not.)

Hope this helps! :heart:

**Comment by xoofx** [comment]
@kivikakk thanks for the precision, indeed, it makes sense also to make it part of an HTML pass
