### ISSUE TITLE
online cmark-gfm for babelmark?

### ISSUE THREAD

**Issue by xoofx** [github/cmark#67]
Hey,

I'm providing the service http://babelmark.github.io and I was wondering if GitHub could provide a HTTP handler for cmark-gfm so that we can add cmark-gfm to the comparison.

The registry for the URL is in the repository https://github.com/babelmark/babelmark-registry  If you would like to store an encrypted URL, you can send it to me to my email and I will send you back an encrypted URL.

It would be of a great help to track compliance with GFM for all the other implementations!

**Comment by kivikakk** [comment]
Hey there!

I would love to support this. Right now you can already translate GFM to HTML with the [`/markdown` API endpoint](https://developer.github.com/v3/markdown/):

```shell
$ curl https://api.github.com/markdown -XPOST -d'{"text":"Hello, **world**."}'
<p>Hello, <strong>world</strong>.</p>
```

Likewise, there's [`/markdown/raw`](https://developer.github.com/v3/markdown/#render-a-markdown-document-in-raw-mode) if you just want to do a raw POST without JSON:

```shell
$ curl https://api.github.com/markdown/raw -XPOST -H"Content-Type: text/plain" -d"Hello, **world**."
<p>Hello, <strong>world</strong>.</p>
```

I see that babelmark wants a GETtable URL with a query string only. I could try to get an extra request mode added to our API, but it might take a while or not get accepted internally since it'd only be for this one purpose. Would you be willing to accept a PR to [https://github.com/babelmark/babelmark-proxy](babelmark-proxy) that added an extra attribute to `MarkdownEntry` which signalled a POST body-only endpoint (like `/markdown/raw` above)?

**Comment by xoofx** [comment]
Thanks @kivikakk I can likely plug babelmark to this API as a workaround. As babelmark displays also the version number, where I can fetch the `cmark-gfm` version actually used? Looks like the only way is to parse top level CMakeLists.txt to get this version... but not sure how there is a way to match it with the GitHub /markdown API exposed...

**Comment by kivikakk** [comment]
Hey @xoofx; opened some suggested PRs at babelmark/babelmark-proxy#1 and babelmark/babelmark-registry#5. Feel free to use or drop as you see fit!

We currently don't expose a cmark version anywhere; we use [commonmarker](https://github.com/gjtorikian/commonmarker) to actually call `cmark-gfm` from Ruby. This is something that'd be useful to have, so stay tuned; I'll try to get a version number from that bubbled up, which in turn will refer to a specific `cmark-gfm` SHA.

**Comment by xoofx** [comment]
cool, thanks! will have a look!

**Comment by kivikakk** [comment]
I have an internal PR opened to add an `X-CommonMarker-Version` header to the Markdown API responses. I'll let you know how it goes.

**Comment by kivikakk** [comment]
Thank you so much for helping make this happen so fast!
