### ISSUE TITLE
Links with stars are misparsed

### ISSUE THREAD

**Issue by DavidBruant** [github/cmark#72]
`https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*` is a [valid url that leads to a webpage](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*), but the parser used in issues leaves the * behind as demonstrated here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

**Comment by kivikakk** [comment]
Indeed; we can't support all link types as autolinked in bare text, because there's too great a chance of confusion in the parser. We [exclude trailing `?!.,:*_~'"`](https://github.com/github/cmark/blob/0c6d1c4baa5b4152717b5b4d72463ec1d1910bf4/extensions/autolink.c#L58-L59). Try using the explicit autolink syntax, `<https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*>`.

**Comment by DavidBruant** [comment]
I didn't know bout the explicit autolink syntax, thanks a lot!
